### ISSUE TITLE
How to perform a pairwise TNI

### ISSUE THREAD

**Issue by elzerac** [chjp/SISProkaryotes#1]
Hello, 

I would like to calculate the TNI between two genomes that I have sequenced. I am wondering if there is a way to use your script without downloading the databases.  

Could you please help me figure out how I could do this? 

Thank you! 

Elze

**Comment by chjp** [comment]
Hi,

Thank you for your interest in TNI. The sub function TNI in SISP.pl can calculate TNI between the two genomes without the database. If you still want to do this analysis, I can tweak the script for you.
